import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import SideNavigation from "./components/navigation/sideNavigation";
import "./globals.css";
import SideMenuFilter from "./components/sideFilter/sideMenuFilter";
import { Toaster } from "react-hot-toast";
import SearchBar from "./components/searchBar/searchBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SideNavigation />
        <SearchBar />
        <SideMenuFilter />
        {children}
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
